[2020-04-01 18:13:19,331] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: atvt.dummy_task 2020-04-01T09:10:00+00:00 [queued]>
[2020-04-01 18:13:19,336] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: atvt.dummy_task 2020-04-01T09:10:00+00:00 [queued]>
[2020-04-01 18:13:19,336] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2020-04-01 18:13:19,336] {taskinstance.py:867} INFO - Starting attempt 1 of 2
[2020-04-01 18:13:19,337] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2020-04-01 18:13:19,592] {taskinstance.py:887} INFO - Executing <Task(DummyOperator): dummy_task> on 2020-04-01T09:10:00+00:00
[2020-04-01 18:13:19,602] {standard_task_runner.py:53} INFO - Started process 110395 to run task
[2020-04-01 18:13:19,751] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: atvt.dummy_task 2020-04-01T09:10:00+00:00 [running]> bi02.com
[2020-04-01 18:13:19,765] {taskinstance.py:1048} INFO - Marking task as SUCCESS.dag_id=atvt, task_id=dummy_task, execution_date=20200401T091000, start_date=20200401T091319, end_date=20200401T091319
[2020-04-01 18:13:29,242] {logging_mixin.py:112} INFO - [2020-04-01 18:13:29,241] {local_task_job.py:103} INFO - Task exited with return code 0
